orbs:
  sam: circleci/aws-sam-serverless@1.0.0
version: 2.1

jobs:
  build_and_deploy:
    executor: sam/default
    steps:
      - checkout
      - run: pip install aws-sam-cli==1.1.0
      - run: sam build
      - run: sam deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_and_deploy