orbs:
  sam: circleci/aws-sam-serverless@1.0.0
version: 2.1

jobs:
  build_and_deploy:
    executor: sam/default
    steps:
      - checkout
      - run: pip install aws-sam-cli==1.1.0
      - run: sam build
      - sam/deploy:
          name: deploy-production
          stack-name: production-stack
          template: ./template.yml
          s3-bucket: aws-sam-cli-managed-default-samclisourcebucket-1at4ufhrnu0h5

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_and_deploy