orbs:
  sam: circleci/aws-sam-serverless@1.0.0
version: 2.1

jobs:
  build_and_deploy:
    executor: sam/default
    steps:
      - checkout
      - run:
          command: |
            sudo apt install libssl-dev
            git clone git://github.com/pyenv/pyenv-update.git $(pyenv root)/plugins/pyenv-update
            pyenv update
            pyenv install 3.7.5
      - run:
          command: |
            pyenv versions
            pyenv global 3.7.5
      - run: pip install aws-sam-cli==1.1.0
      - run: sam build
      - run: sam deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_and_deploy