orbs:
  sam: circleci/aws-sam-serverless@1.0.0
version: 2.1
workflows:
  test_and_deploy:
    jobs:
      - sam/deploy:
          name: deploy-production
          stack-name: production-stack
          template: ./template.yml
          s3-bucket: aws-sam-cli-managed-default-samclisourcebucket-1at4ufhrnu0h5